---
- name: install konsole
  apk:
    name: konsole
    update_cache: true

- name: enable needed modules
  copy:
    src: modules
    dest: /etc/modules

- name: copy gnss-config
  copy:
    src: gnss-config
    dest: /etc/gnss-share.conf

- name: create dir for gnss
  file:
    path: /var/cache/gnss-share
    state: directory

- name: and enable gnss
  command:
    cmd: "rc-update add gnss-share"

- name: geoclue config
  copy:
    src: geoclue-config
    dest: /etc/geoclue/geoclue.conf

- name: udev rules
  copy:
    src: udev-usb
    dest: /etc/udev/rules.d/99-usb-serial.rules

- name: disable screen blanking
  copy:
    src: powerdevilrc
    dest: /home/user/.config/powerdevilrc

- name: disable screen locking
  copy:
    src: kscreenlockerrc
    dest: /home/user/.config/kscreenlockerrc

- name: doesktop image
  copy:
    src: rustywallpaper.jpeg
    dest: /home/user/Pictures/rustywallpaper.jpeg
- name: desktop image 2
  copy:
    src: rustywallpaper2.jpeg
    dest: /home/user/Pictures/rustywallpaper2.jpeg

- name: desktop layout
  copy:
    src: MyDesktop.json
    dest:  /home/user/Documents/MyDesktopLayout.json

#- name: symlink modprobe for waydroid
#  file:
#    src: /sbin/modprobe
#    dest: /usr/bin/modprobe
#    state: link

- name: copy bt autostart
  copy:
    src: btstart.desktop
    dest: /home/user/.config/autostart/
    owner: user
    group: user

- name: copy env dmp script
  copy:
    src: capture_env.sh
    dest: /usr/local/bin
    mode: 0755

- name: and the autostart 
  copy:
    src: envdump.desktop
    dest: /home/user/.config/autostart/

#- name: disable wifi powersave
#  copy:
#    src: default-wifi-powersave-on.conf
#    dest: /etc/NetworkManager/conf.d/
