---
- name: copy the script
  copy:
    src: pwr-mgr3.py
    dest: /usr/local/bin/
    mode: 0755
- name: copy the init script
  copy:
    src: pwr-mgr3.service
    dest: /etc/systemd/system/pwr-mgr3.service
- name: Enable the power management
  ansible.builtin.systemd:
      name: pwr-mgr3.service
      state: started
      enabled: yes
